# Generated by Django 5.1.2 on 2024-10-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CexCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, db_comment='Descripci≤n corta para SEO', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(db_comment='producto ½product╗ o servicio ½service╗', max_length=20)),
                ('credits', models.FloatField(blank=True, db_comment='Creitos solo para terce nivel', null=True)),
                ('def_type', models.CharField(max_length=5)),
                ('def_price', models.FloatField()),
                ('do_related', models.TextField()),
                ('coins_coefficient', models.FloatField(blank=True, null=True)),
                ('min_coins', models.IntegerField(blank=True, null=True)),
                ('max_coins', models.IntegerField(blank=True, null=True)),
                ('industry_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cex_category',
                'managed': False,
            },
        ),
    ]
