# Generated by Django 5.1.2 on 2025-02-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_cexserviceproduct_cexstand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CexServiceProduct',
        ),
        migrations.DeleteModel(
            name='CexStand',
        ),
    ]
