# Generated by Django 5.1.2 on 2025-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0003_cexplan_cexsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CexCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cex_country',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CexQuotes',
        ),
        migrations.DeleteModel(
            name='CexServiceProduct',
        ),
    ]
