# Generated by Django 5.1.2 on 2025-10-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0004_cexcountry_delete_cexquotes_delete_cexserviceproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CexExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_id', models.IntegerField()),
                ('url_image', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('code', models.TextField(blank=True, null=True)),
                ('date_final', models.DateField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cex_exhibition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.IntegerField(db_comment='dektrium', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='dektrium', max_length=255, null=True)),
                ('public_email', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='dektrium', max_length=255, null=True)),
                ('gravatar_email', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='dektrium', max_length=255, null=True)),
                ('gravatar_id', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='dektrium', max_length=32, null=True)),
                ('location', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='localidad lat,lng', max_length=255, null=True)),
                ('website', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='Sitio web', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, db_collation='utf8mb3_general_ci', db_comment='Biograf├¡a', null=True)),
                ('timezone', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='Zona horaria', max_length=40, null=True)),
                ('cex_first_name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('cex_last_name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='Apellido', max_length=100, null=True)),
                ('cex_contact_phone', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='Tel├®fono de contacto', max_length=45, null=True)),
                ('cex_newsfeed_subscription', models.TextField(blank=True, db_comment='Subscripci├│n a noticias', null=True)),
                ('cex_city', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_comment='Ciudad', max_length=45, null=True)),
                ('cex_country_id', models.IntegerField(blank=True, db_comment='Pais Id', null=True)),
                ('cex_province_id', models.IntegerField(blank=True, null=True)),
                ('cex_status', models.CharField(db_comment='Status del usuario', max_length=25)),
                ('cex_comments', models.TextField(blank=True, null=True)),
                ('cex_home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('cex_billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('cex_ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('cex_contact_home_phone', models.CharField(max_length=45)),
                ('email_visitor_sent', models.IntegerField()),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
    ]
