from django.db import models
from apps.stand.models import CexCountry
from apps.dashboard.fields import BitBooleanField

class CexServiceProduct(models.Model):
    stand_id = models.IntegerField()
    category_id = models.IntegerField()
    seo_id = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    brand = models.CharField(max_length=255, blank=True, null=True)
    origin = models.CharField(max_length=45, blank=True, null=True)
    specifications = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    type = models.CharField(max_length=20, db_comment='producto ┬½product┬╗ o servicio ┬½service┬╗')
    active = BitBooleanField(default=True)
    upc = models.CharField(max_length=120)
    price = models.FloatField()
    item_type = models.CharField(max_length=5, blank=True, null=True)
    creation_date = models.DateTimeField()
    image = models.CharField(max_length=255, blank=True, null=True)
    images = models.TextField(blank=True, null=True)
    url_web = models.CharField(max_length=150, blank=True, null=True)
    slug = models.CharField(max_length=45)
    counter = models.IntegerField(default=0,blank=True,db_comment='Contador de accesos\n')
    promoted = BitBooleanField(default=False, db_comment='Produto es promovido')
    highlight = BitBooleanField(default=False)  # This field type is a guess.
    delivery_to = models.CharField(max_length=255, blank=True, null=True)
    tour_switch = models.IntegerField(default=0,db_comment='Switch tour virtual ')
    bnb_switch_switch = models.IntegerField(default=0,db_comment='Switch c├│digo bnb')
    vr_tour = models.TextField(blank=True,db_comment='C├│digo tour virtual')
    bnb_code = models.TextField(blank=True,db_comment='C├│digo bnb')
    position = models.IntegerField(default=0,db_comment='Posici├│n del producto')
    discount = models.FloatField(default=0)
    has_discount = models.IntegerField(default=0)
    delivery_cost = models.FloatField(default=0)
    inventory = models.IntegerField(default=0)
    can_sell = models.IntegerField(default=0)
    price_contruex = models.FloatField(default=0)
    price_public_sale = models.FloatField(default=0)
    fixed = models.IntegerField(default=0,blank=True, null=True)
    country = models.ForeignKey('stand.CexCountry', on_delete=models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'cex_service_product'
        

class CexQuotes(models.Model):
    stand_id = models.IntegerField()
    service_product_id = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=32)
    ispaid = models.IntegerField(db_column='isPaid')  # Field name made lowercase.
    quoted_by = models.CharField(max_length=255)
    quoted_on = models.DateTimeField()
    quote_email = models.CharField(max_length=150, blank=True, null=True)
    quote_phone = models.CharField(max_length=45, blank=True, null=True)
    quote_notes = models.TextField(blank=True, null=True)
    quote_preferred_contact = models.CharField(max_length=8)
    quote_time_of_contact = models.CharField(max_length=100, blank=True, null=True)
    service_product_no_of_items = models.IntegerField()
    quote_place_of_contact = models.CharField(max_length=255, blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    quote_price = models.FloatField(db_comment='Precio del φtem')
    quote_c1 = models.IntegerField(blank=True, null=True, db_comment='Categorφa 1')
    quote_c2 = models.IntegerField(blank=True, null=True, db_comment='Categorφa 2')
    quote_c3 = models.IntegerField(blank=True, null=True, db_comment='Categorφa 3')
    quote_country = models.IntegerField()
    quote_province = models.IntegerField()
    quote_created = models.DateTimeField()
    quote_opened = models.DateTimeField(blank=True, null=True)
    quote_edited = models.DateTimeField(blank=True, null=True)
    quote_closed = models.DateTimeField(blank=True, null=True)
    number_coins = models.IntegerField(blank=True, null=True)
    user_id = models.IntegerField(blank=True, null=True)
    quote_type = models.CharField(max_length=8)
    payed = models.IntegerField()
    latitud = models.CharField(max_length=30, blank=True, null=True)
    longitud = models.CharField(max_length=30, blank=True, null=True)
    project_advance = models.CharField(max_length=25, blank=True, null=True)
    project_type = models.CharField(max_length=33, blank=True, null=True)
    project_finance_status = models.CharField(max_length=26, blank=True, null=True)
    project_value = models.CharField(max_length=17, blank=True, null=True)
    project_name = models.CharField(max_length=50, blank=True, null=True)
    has_budget = models.IntegerField(blank=True, null=True)
    budget = models.FloatField(blank=True, null=True)
    project_responsable = models.CharField(max_length=50, blank=True, null=True)
    project_email = models.CharField(max_length=50, blank=True, null=True)
    project_phone = models.IntegerField(blank=True, null=True)
    project_qualification = models.IntegerField(blank=True, null=True)
    comerce = models.IntegerField(blank=True, null=True)
    qualification_description = models.TextField(blank=True, null=True)
    qualification_status = models.CharField(max_length=16, blank=True, null=True)
    qualification_date = models.DateField(blank=True, null=True)
    manual_admin_quote = models.IntegerField(blank=True, null=True)
    install_time = models.CharField(max_length=250, blank=True, null=True)
    pay_form = models.CharField(max_length=250, blank=True, null=True)
    same_client_address = models.IntegerField(blank=True, null=True)
    delivered_place = models.CharField(max_length=255, blank=True, null=True)
    has_transport = models.IntegerField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    cex_client_crm_id = models.IntegerField(blank=True, null=True)
    created_by_stand = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'cex_quotes'
        db_table_comment = 'gesti≤n de cotizaciones'