# Generated by Django 5.1.2 on 2024-10-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CexLandingPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('seo_description', models.CharField(max_length=255)),
                ('front_block', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.CharField(max_length=255)),
                ('has_slider_revolution', models.IntegerField()),
                ('slider_revolution_file', models.CharField(max_length=255)),
                ('slider_revolution_date', models.DateTimeField(blank=True, null=True)),
                ('slider_id', models.IntegerField(blank=True, null=True)),
                ('tour_switch', models.IntegerField()),
                ('tour_virtual_code', models.TextField(blank=True, null=True)),
                ('foot_bar', models.IntegerField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_title', models.TextField(blank=True, null=True)),
                ('spaces_public', models.IntegerField()),
                ('is_public', models.IntegerField()),
                ('adsense_enabled', models.IntegerField()),
                ('adsense_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cex_landing_pages',
                'managed': False,
            },
        ),
    ]
