# Generated by Django 5.1.2 on 2025-10-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CexInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('organization', models.CharField(blank=True, max_length=80, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=45)),
                ('from_field', models.CharField(blank=True, db_column='from', max_length=120, null=True)),
                ('to', models.CharField(blank=True, max_length=120, null=True)),
                ('stand_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mailed_it', models.DateTimeField()),
                ('country_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cex_inbox',
                'managed': False,
            },
        ),
    ]
