# Generated by Django 5.1.2 on 2025-10-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CexQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_id', models.IntegerField()),
                ('service_product_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('ispaid', models.IntegerField(db_column='isPaid')),
                ('quoted_by', models.CharField(max_length=255)),
                ('quoted_on', models.DateTimeField()),
                ('quote_email', models.CharField(blank=True, max_length=150, null=True)),
                ('quote_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('quote_notes', models.TextField(blank=True, null=True)),
                ('quote_preferred_contact', models.CharField(max_length=8)),
                ('quote_time_of_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('service_product_no_of_items', models.IntegerField()),
                ('quote_place_of_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('quote_price', models.FloatField(db_comment='Precio del ├¡tem')),
                ('quote_c1', models.IntegerField(blank=True, db_comment='Categor├¡a 1', null=True)),
                ('quote_c2', models.IntegerField(blank=True, db_comment='Categor├¡a 2', null=True)),
                ('quote_c3', models.IntegerField(blank=True, db_comment='Categor├¡a 3', null=True)),
                ('quote_country', models.IntegerField()),
                ('quote_province', models.IntegerField()),
                ('quote_created', models.DateTimeField()),
                ('quote_opened', models.DateTimeField(blank=True, null=True)),
                ('quote_edited', models.DateTimeField(blank=True, null=True)),
                ('quote_closed', models.DateTimeField(blank=True, null=True)),
                ('number_coins', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('quote_type', models.CharField(max_length=8)),
                ('payed', models.IntegerField()),
                ('latitud', models.CharField(blank=True, max_length=30, null=True)),
                ('longitud', models.CharField(blank=True, max_length=30, null=True)),
                ('project_advance', models.CharField(blank=True, max_length=25, null=True)),
                ('project_type', models.CharField(blank=True, max_length=33, null=True)),
                ('project_finance_status', models.CharField(blank=True, max_length=26, null=True)),
                ('project_value', models.CharField(blank=True, max_length=17, null=True)),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('has_budget', models.IntegerField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('project_responsable', models.CharField(blank=True, max_length=50, null=True)),
                ('project_email', models.CharField(blank=True, max_length=50, null=True)),
                ('project_phone', models.IntegerField(blank=True, null=True)),
                ('project_qualification', models.IntegerField(blank=True, null=True)),
                ('comerce', models.IntegerField(blank=True, null=True)),
                ('qualification_description', models.TextField(blank=True, null=True)),
                ('qualification_status', models.CharField(blank=True, max_length=16, null=True)),
                ('qualification_date', models.DateField(blank=True, null=True)),
                ('manual_admin_quote', models.IntegerField(blank=True, null=True)),
                ('install_time', models.CharField(blank=True, max_length=250, null=True)),
                ('pay_form', models.CharField(blank=True, max_length=250, null=True)),
                ('same_client_address', models.IntegerField(blank=True, null=True)),
                ('delivered_place', models.CharField(blank=True, max_length=255, null=True)),
                ('has_transport', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('cex_client_crm_id', models.IntegerField(blank=True, null=True)),
                ('created_by_stand', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cex_quotes',
                'db_table_comment': 'gesti├│n de cotizaciones',
                'managed': False,
            },
        ),
    ]
