# Generated by Django 5.1.2 on 2025-02-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CexCategory',
        ),
        migrations.DeleteModel(
            name='CexStand',
        ),
    ]
