# Generated by Django 5.1.2 on 2025-03-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CexStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('stand_type_id', models.IntegerField()),
                ('seo_id', models.IntegerField()),
                ('stand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cex_stand',
                'managed': False,
            },
        ),
    ]
