# Generated by Django 5.1.2 on 2025-10-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_s3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CexServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('seo_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cex_service_product',
            },
        ),
    ]
