# Generated by Django 5.1.2 on 2025-10-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CexCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_id', models.IntegerField()),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('seo_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img_pdf', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('country_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cex_catalog',
                'managed': False,
            },
        ),
    ]
