# Generated by Django 5.1.2 on 2024-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_collation='utf8mb3_general_ci', max_length=255, unique=True)),
                ('email', models.CharField(db_collation='utf8mb3_general_ci', max_length=255, unique=True)),
                ('password_hash', models.CharField(db_collation='utf8mb3_general_ci', max_length=60)),
                ('auth_key', models.CharField(db_collation='utf8mb3_general_ci', max_length=32)),
                ('confirmed_at', models.IntegerField(blank=True, null=True)),
                ('unconfirmed_email', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
                ('blocked_at', models.IntegerField(blank=True, null=True)),
                ('registration_ip', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=45, null=True)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('last_login_at', models.IntegerField(blank=True, null=True)),
                ('stand_id', models.IntegerField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(db_comment='terminos y condiciones aceptados o no aceptados')),
                ('stand_assign', models.IntegerField(blank=True, null=True)),
                ('new_password', models.CharField(db_collation='utf8mb3_general_ci', max_length=60)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
