# Generated by Django 5.1.2 on 2025-03-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CexUserOpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_collation='utf8mb3_general_ci', max_length=255, unique=True)),
                ('otp', models.CharField(db_collation='utf8mb3_general_ci', max_length=6)),
                ('created_at', models.IntegerField()),
                ('expires_at', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cex_user_opt',
                'managed': False,
            },
        ),
    ]
